[versions]

activityCompose = "1.10.1"
agp = "8.11.1"
coreSplashscreen = "1.0.1"
firebaseBom = "34.2.0"
generativeai = "0.9.0"
glanceAppwidget = "1.1.1"
glanceMaterial3 = "1.1.1"
hiltCompiler = "1.3.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"
hilt = "2.52"

coreKtx = "1.13.1"
datastorePreferences = "1.1.1"
appcompat = "1.7.0"
lottieCompose = "6.6.7"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.2.1"
lifecycle = "2.8.3"
lottie = "6.4.1"
material3 = "1.3.2"
materialIconsExtended = "1.7.8"
room = "2.6.1"
retrofit = "2.11.0"
okhttp = "4.12.0"

junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
coroutinesTest = "1.8.1"
runtime = "1.8.3"
translate = "17.0.3"
uiToolingPreview = "1.8.3"
runtimeLivedata = "1.8.3"
lifecycleService = "2.9.2"
navigation = "2.9.3"
hiltNavigationCompose = "1.2.0"
glancePreview = "1.1.1"



[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glanceMaterial3" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }



material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
translate = { module = "com.google.mlkit:translate", version.ref = "translate" }
ui = { module = "androidx.compose.ui:ui", version.ref = "uiToolingPreview" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiToolingPreview" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glancePreview" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }